FROM node:10.21.0-alpine3.11 as build-stage
WORKDIR /app

COPY package*json ./

COPY .npmrc .
COPY .yarnrc .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.13.12-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html

COPY --from=build-stage /app/jvjr-entrypoint.sh /
COPY jvjr-env.json /
RUN chmod +x /jvjr-entrypoint.sh

EXPOSE 80

ENTRYPOINT [ "/jvjr-entrypoint.sh", "/usr/share/nginx/html/js", "app" ]
CMD ["nginx", "-g", "daemon off;"]

