/**
 * Docker Real Build Integration Tests - Phase 4
 *
 * Verifies the full Docker lifecycle:
 * 1. Create a minimal frontend project
 * 2. Apply jvjr-docker-env (generates Dockerfile, entrypoint, jvjr-env.json)
 * 3. Run docker build (real image build)
 * 4. Run docker run and verify env var substitution works
 * 5. Cleanup image
 *
 * Requires: Docker daemon running
 * Timeout: 120s per test (image pull + build)
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { execSync, execFileSync } from 'child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PROJECT_ROOT = path.resolve(__dirname, '../..');
const DOCKER_BUILD_DIR = path.resolve(PROJECT_ROOT, 'tests/integration/docker-build-real');
const IMAGE_PREFIX = 'jvjr-test';

// --- Docker availability check ---
function checkDockerAvailable() {
    try {
        execSync('docker info', { stdio: 'ignore', timeout: 5000 });
        return true;
    } catch {
        return false;
    }
}

const DOCKER_AVAILABLE = checkDockerAvailable();

function runCli(args, cwd) {
    return execSync(
        `node ${path.join(PROJECT_ROOT, 'bin/jvjr')} ${args}`,
        { cwd, encoding: 'utf-8', timeout: 10000 }
    );
}

function dockerBuild(imageTag, contextDir) {
    return execSync(
        `docker build -t ${imageTag} -f Dockerfile-jvjr .`,
        { cwd: contextDir, encoding: 'utf-8', timeout: 180000 }
    );
}

function dockerRun(imageTag, envVars, cmd) {
    const envFlags = Object.entries(envVars)
        .map(([k, v]) => `-e "${k}=${v}"`)
        .join(' ');
    return execSync(
        `docker run --rm ${envFlags} --entrypoint sh ${imageTag} -c "${cmd}"`,
        { encoding: 'utf-8', timeout: 30000 }
    );
}

function dockerRmi(imageTag) {
    try {
        execSync(`docker rmi ${imageTag}`, { stdio: 'ignore', timeout: 15000 });
    } catch {
        // ignore cleanup failures
    }
}

function imageExists(imageTag) {
    try {
        execSync(`docker image inspect ${imageTag}`, { stdio: 'ignore', timeout: 5000 });
        return true;
    } catch {
        return false;
    }
}

// --- Build script restoration after jvjr --start ---
// jvjr --start prepends "jvjr --build && " to the build script.
// Inside Docker, jvjr is not installed (it's a host tool), so we restore
// the build script to just "sh build.sh" after --start.
// jvjr-env.json was already generated by --start on the host.
function fixBuildScriptForDocker(projectDir, originalBuildScript) {
    const pkgPath = path.join(projectDir, 'package.json');
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
    pkg.scripts.build = originalBuildScript;
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));
}

// --- Minimal Vue project factory ---
function createMinimalVueProject(projectDir, envVars) {
    fs.mkdirSync(path.join(projectDir, 'src'), { recursive: true });

    // package.json - build script uses build.sh (POSIX sh, no deps)
    fs.writeFileSync(
        path.join(projectDir, 'package.json'),
        JSON.stringify({
            name: 'vue-docker-test',
            version: '1.0.0',
            scripts: { build: 'sh build.sh' }
        }, null, 2)
    );

    // .env - Vue App vars
    const envContent = Object.entries(envVars)
        .map(([k, v]) => `${k}=${v}`)
        .join('\n') + '\n';
    fs.writeFileSync(path.join(projectDir, '.env'), envContent);

    // build.sh - creates dist with JS placeholders for runtime substitution
    // The JS file embeds $VUE_APP_* literals that entrypoint replaces at runtime
    const envKeys = Object.keys(envVars);
    const jsContent = envKeys
        .map(k => {
            const short = k.replace(/^VUE_APP_/, '');
            return `${short.toLowerCase()}:"$${k}"`;
        })
        .join(',');

    fs.writeFileSync(
        path.join(projectDir, 'build.sh'),
        [
            '#!/bin/sh',
            'mkdir -p dist/js',
            `printf 'window.config={${jsContent}};' > dist/js/app.main.js`,
            "printf '<html><body><script src=\"/js/app.main.js\"></script></body></html>' > dist/index.html"
        ].join('\n') + '\n'
    );
}

// --- Minimal React project factory ---
function createMinimalReactProject(projectDir, envVars) {
    fs.mkdirSync(path.join(projectDir, 'src'), { recursive: true });

    fs.writeFileSync(
        path.join(projectDir, 'package.json'),
        JSON.stringify({
            name: 'react-docker-test',
            version: '1.0.0',
            scripts: { build: 'sh build.sh' }
        }, null, 2)
    );

    const envContent = Object.entries(envVars)
        .map(([k, v]) => `${k}=${v}`)
        .join('\n') + '\n';
    fs.writeFileSync(path.join(projectDir, '.env'), envContent);

    const envKeys = Object.keys(envVars);
    const jsContent = envKeys
        .map(k => {
            const short = k.replace(/^REACT_APP_/, '');
            return `${short.toLowerCase()}:"$${k}"`;
        })
        .join(',');

    fs.writeFileSync(
        path.join(projectDir, 'build.sh'),
        [
            '#!/bin/sh',
            'mkdir -p dist/js',
            `printf 'window.config={${jsContent}};' > dist/js/app.main.js`,
            "printf '<html><body><script src=\"/js/app.main.js\"></script></body></html>' > dist/index.html"
        ].join('\n') + '\n'
    );
}

// =============================================================================
// Tests
// =============================================================================

const maybeDescribe = DOCKER_AVAILABLE ? describe : describe.skip;

maybeDescribe('Phase 4: Docker Real Build - Vue App', () => {
    jest.setTimeout(180000);

    const imageTag = `${IMAGE_PREFIX}-vue-${Date.now()}`;
    const projectDir = path.join(DOCKER_BUILD_DIR, 'vue-app');

    const VUE_ENV_VARS = {
        VUE_APP_API_URL: 'http://build-time-placeholder.local',
        VUE_APP_TITLE: 'BUILD_PLACEHOLDER',
        VUE_APP_VERSION: 'BUILD_PLACEHOLDER_VERSION'
    };

    const RUNTIME_VARS = {
        VUE_APP_API_URL: 'https://prod.api.example.com',
        VUE_APP_TITLE: 'Production App',
        VUE_APP_VERSION: '3.2.1'
    };

    beforeAll(() => {
        if (fs.existsSync(projectDir)) {
            fs.rmSync(projectDir, { recursive: true, force: true });
        }
        fs.mkdirSync(projectDir, { recursive: true });
        createMinimalVueProject(projectDir, VUE_ENV_VARS);
        runCli('--start', projectDir);
        // jvjr is a host tool, not available inside Docker container.
        // jvjr-env.json is already generated; restore build script to sh build.sh only.
        fixBuildScriptForDocker(projectDir, 'sh build.sh');
        dockerBuild(imageTag, projectDir);
    });

    afterAll(() => {
        dockerRmi(imageTag);
    });

    test('docker image is built successfully', () => {
        expect(imageExists(imageTag)).toBe(true);
    });

    test('image contains jvjr-env.json at /jvjr-env.json', () => {
        const output = dockerRun(imageTag, {}, 'cat /jvjr-env.json');
        const envJson = JSON.parse(output);
        expect(envJson.API_URL).toBe('$VUE_APP_API_URL');
        expect(envJson.TITLE).toBe('$VUE_APP_TITLE');
        expect(envJson.VERSION).toBe('$VUE_APP_VERSION');
    });

    test('image contains compiled JS at /usr/share/nginx/html/js/app.main.js', () => {
        const output = dockerRun(imageTag, {}, 'cat /usr/share/nginx/html/js/app.main.js');
        // Should contain literal $VUE_APP_* placeholders (not yet substituted)
        expect(output).toContain('$VUE_APP_API_URL');
        expect(output).toContain('$VUE_APP_TITLE');
    });

    test('image contains index.html at /usr/share/nginx/html/index.html', () => {
        const output = dockerRun(imageTag, {}, 'cat /usr/share/nginx/html/index.html');
        expect(output).toContain('app.main.js');
    });

    test('jvjr-entrypoint.sh is executable in image', () => {
        const output = dockerRun(imageTag, {}, 'ls -la /jvjr-entrypoint.sh');
        expect(output).toContain('jvjr-entrypoint.sh');
        // Verify executable bit
        expect(output).toMatch(/^-rwx/m);
    });

    test('envsubst replaces VUE_APP_API_URL at runtime', () => {
        // envsubst without args replaces all env vars found in file
        const cmd = 'cp /usr/share/nginx/html/js/app.main.js /tmp/app.main.js && envsubst < /tmp/app.main.js';
        const output = dockerRun(imageTag, { VUE_APP_API_URL: RUNTIME_VARS.VUE_APP_API_URL }, cmd);
        expect(output).toContain('https://prod.api.example.com');
        expect(output).not.toContain('$VUE_APP_API_URL');
    });

    test('envsubst replaces all VUE_APP_* vars at runtime', () => {
        const cmd = 'cp /usr/share/nginx/html/js/app.main.js /tmp/app.main.js && envsubst < /tmp/app.main.js';
        const output = dockerRun(imageTag, RUNTIME_VARS, cmd);
        expect(output).toContain('https://prod.api.example.com');
        expect(output).toContain('Production App');
        expect(output).toContain('3.2.1');
        expect(output).not.toContain('$VUE_APP_');
    });

    test('nginx binary is available in image', () => {
        const output = dockerRun(imageTag, {}, 'nginx -v 2>&1 || true');
        expect(output).toMatch(/nginx/i);
    });
});

maybeDescribe('Phase 4: Docker Real Build - React App', () => {
    jest.setTimeout(180000);

    const imageTag = `${IMAGE_PREFIX}-react-${Date.now()}`;
    const projectDir = path.join(DOCKER_BUILD_DIR, 'react-app');

    const REACT_ENV_VARS = {
        REACT_APP_API_URL: 'http://react-build-placeholder.local',
        REACT_APP_API_KEY: 'PLACEHOLDER_KEY',
        REACT_APP_VERSION: '1.0.0-placeholder'
    };

    const RUNTIME_REACT_VARS = {
        REACT_APP_API_URL: 'https://react-prod.api.example.com',
        REACT_APP_API_KEY: 'prod-secret-key-abc123',
        REACT_APP_VERSION: '2.5.0'
    };

    beforeAll(() => {
        if (fs.existsSync(projectDir)) {
            fs.rmSync(projectDir, { recursive: true, force: true });
        }
        fs.mkdirSync(projectDir, { recursive: true });
        createMinimalReactProject(projectDir, REACT_ENV_VARS);
        runCli('--start', projectDir);
        fixBuildScriptForDocker(projectDir, 'sh build.sh');
        dockerBuild(imageTag, projectDir);
    });

    afterAll(() => {
        dockerRmi(imageTag);
    });

    test('docker image is built successfully', () => {
        expect(imageExists(imageTag)).toBe(true);
    });

    test('image contains jvjr-env.json with REACT_APP_* references', () => {
        const output = dockerRun(imageTag, {}, 'cat /jvjr-env.json');
        const envJson = JSON.parse(output);
        expect(envJson.API_URL).toBe('$REACT_APP_API_URL');
        expect(envJson.API_KEY).toBe('$REACT_APP_API_KEY');
        expect(envJson.VERSION).toBe('$REACT_APP_VERSION');
    });

    test('envsubst replaces all REACT_APP_* vars at runtime', () => {
        const cmd = 'cp /usr/share/nginx/html/js/app.main.js /tmp/app.main.js && envsubst < /tmp/app.main.js';
        const output = dockerRun(imageTag, RUNTIME_REACT_VARS, cmd);
        expect(output).toContain('https://react-prod.api.example.com');
        expect(output).toContain('prod-secret-key-abc123');
        expect(output).toContain('2.5.0');
        expect(output).not.toContain('$REACT_APP_');
    });
});

maybeDescribe('Phase 4: Docker Runtime - Env Var Isolation', () => {
    jest.setTimeout(180000);

    const imageTag = `${IMAGE_PREFIX}-isolation-${Date.now()}`;
    const projectDir = path.join(DOCKER_BUILD_DIR, 'isolation-app');

    beforeAll(() => {
        if (fs.existsSync(projectDir)) {
            fs.rmSync(projectDir, { recursive: true, force: true });
        }
        fs.mkdirSync(projectDir, { recursive: true });
        createMinimalVueProject(projectDir, {
            VUE_APP_SECRET: 'build-time-value',
            VUE_APP_PUBLIC: 'build-time-public'
        });
        runCli('--start', projectDir);
        fixBuildScriptForDocker(projectDir, 'sh build.sh');
        dockerBuild(imageTag, projectDir);
    });

    afterAll(() => {
        dockerRmi(imageTag);
    });

    test('runtime env var overrides build-time placeholder', () => {
        const cmd = 'cp /usr/share/nginx/html/js/app.main.js /tmp/app.main.js && envsubst < /tmp/app.main.js';
        const output = dockerRun(imageTag, {
            VUE_APP_SECRET: 'runtime-secret-value',
            VUE_APP_PUBLIC: 'runtime-public-value'
        }, cmd);
        expect(output).toContain('runtime-secret-value');
        expect(output).toContain('runtime-public-value');
        expect(output).not.toContain('build-time-value');
        expect(output).not.toContain('BUILD_PLACEHOLDER');
    });

    test('unset runtime vars leave placeholder empty string', () => {
        // envsubst replaces unset vars with empty string
        const cmd = 'cp /usr/share/nginx/html/js/app.main.js /tmp/app.main.js && envsubst < /tmp/app.main.js';
        const output = dockerRun(imageTag, { VUE_APP_SECRET: 'only-secret' }, cmd);
        expect(output).toContain('only-secret');
        // VUE_APP_PUBLIC should be replaced by empty string (envsubst behavior for unset vars)
        expect(output).not.toContain('$VUE_APP_PUBLIC');
    });

    test('different container runs are isolated (no shared state)', () => {
        const cmd = 'cp /usr/share/nginx/html/js/app.main.js /tmp/app.main.js && envsubst < /tmp/app.main.js';

        const run1 = dockerRun(imageTag, { VUE_APP_SECRET: 'run-one-value', VUE_APP_PUBLIC: 'pub' }, cmd);
        const run2 = dockerRun(imageTag, { VUE_APP_SECRET: 'run-two-value', VUE_APP_PUBLIC: 'pub' }, cmd);

        expect(run1).toContain('run-one-value');
        expect(run2).toContain('run-two-value');
        expect(run1).not.toContain('run-two-value');
        expect(run2).not.toContain('run-one-value');
    });
});

maybeDescribe('Phase 4: Docker Build - Uninstall Lifecycle', () => {
    jest.setTimeout(180000);

    const imageTag = `${IMAGE_PREFIX}-lifecycle-${Date.now()}`;
    const projectDir = path.join(DOCKER_BUILD_DIR, 'lifecycle-app');

    beforeAll(() => {
        if (fs.existsSync(projectDir)) {
            fs.rmSync(projectDir, { recursive: true, force: true });
        }
        fs.mkdirSync(projectDir, { recursive: true });
        createMinimalVueProject(projectDir, { VUE_APP_BASE_URL: 'http://localhost' });
        runCli('--start', projectDir);
        fixBuildScriptForDocker(projectDir, 'sh build.sh');
    });

    afterAll(() => {
        dockerRmi(imageTag);
    });

    test('after --start, project can build a Docker image', () => {
        dockerBuild(imageTag, projectDir);
        expect(imageExists(imageTag)).toBe(true);
    });

    test('after --uninstall, Docker files are removed from project', () => {
        runCli('--uninstall', projectDir);
        expect(fs.existsSync(path.join(projectDir, 'Dockerfile-jvjr'))).toBe(false);
        expect(fs.existsSync(path.join(projectDir, 'jvjr-entrypoint.sh'))).toBe(false);
        expect(fs.existsSync(path.join(projectDir, 'jvjr-env.json'))).toBe(false);
    });

    test('after --uninstall, package.json scripts are cleaned', () => {
        const pkg = JSON.parse(
            fs.readFileSync(path.join(projectDir, 'package.json'), 'utf-8')
        );
        expect(pkg.scripts['jvjr-build']).toBeUndefined();
        if (pkg.scripts.build) {
            expect(pkg.scripts.build).not.toContain('jvjr');
        }
    });

    test('after --start again, project rebuilds Docker image', () => {
        runCli('--start', projectDir);
        fixBuildScriptForDocker(projectDir, 'sh build.sh');
        const newTag = `${imageTag}-rebuilt`;
        try {
            dockerBuild(newTag, projectDir);
            expect(imageExists(newTag)).toBe(true);
        } finally {
            dockerRmi(newTag);
        }
    });
});

if (!DOCKER_AVAILABLE) {
    describe('Phase 4: Docker Real Build (SKIPPED - Docker not available)', () => {
        test('Docker daemon is not running', () => {
            console.warn('SKIP: Docker daemon not available. Start Docker to run Phase 4 tests.');
            expect(true).toBe(true);
        });
    });
}
